### ISSUE TITLE
Error when starting for the First time

### ISSUE THREAD

**Issue by clovisd** [Xawirses/PhantomBot#1]
Hey there,

When starting this container for the first time, I get an error and the container just stops:

`
[10-31-2020 @ 17:18:21.361 GMT] The working directory is: /phantombot,
[10-31-2020 @ 17:18:21.418 GMT] Detected Java 11.0.4 running on Linux 5.4.0-52-generic (amd64),
Welcome to the PhantomBot setup process!
If you have any issues please join our Discord!
Discord: https://discord.gg/YKvMd78
PhantomBot has detected that your device is running Linux.
Here's the setup guide for Ubuntu: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/ubuntu
Here's the setup guide for CentOS: https://phantombot.github.io/PhantomBot/guides/#guide=content/setupbot/centos
1. Please enter the bot's Twitch username: [10-31-2020 @ 17:18:21.445 GMT] [ERROR] Failed to setup PhantomBot. Now exiting...,`

I created all the appropriate directories for the bind volumes and can access them. When I try binding to the instance during its first setup, it shuts down before I can actually do anything.

Any advice or help would be appreciated!
Thank you,
-C

**Comment by Xawirses** [comment]
Hello

This container does not allow to use the phantombot setup configuration.
I advise you to do a first start (setup) from your pc, then copy your **botlogin.txt** and **phantombot.db** in the **config** folder of your volume.

I will modify the README to add this information.

Regards

**Comment by clovisd** [comment]
Thank you! 

Will do this. Have a good day.
